/-
Copyright (c) 2026 Jun Yin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jun Yin
-/
import RBM3D.Gauss.FineModel
import RBM3D.Defs.StochDomAt
import RBM3D.Loop.GLoopFlow
import Mathlib.Analysis.Matrix.MeasurableSpace
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.Independence.InfinitePi
import Mathlib.Probability.Independence.ZeroOne
import Mathlib.Probability.Process.Filtration

/-!
# The grid walk: carrier, filtration, independent increments, the transfer law, and the
# per-time transfer between the grid walk and the single-time model

Ticket T2018 (MD-4).  Paper: arXiv:2507.20274, `paper/tex/1_2_Intro_model_result.tex`
(cited `1_2:line`): `(MBM)` `1_2:686`, `(stoch_domination)` `1_2:227–231`.

* Section 8 of the compiled T2002 probe (`RBM3D/Probe/T2002Vocab.lean` at `5d2a4a8` on branch
  `t/T2002`, never merged, lines 937–1035), **copied verbatim** with docstrings and proofs: `PathΩ`,
  `pathP`, `filt`, `gridStep`, `gridTime`, `pathH`, the pins `TransferLaw` and `IndepIncr`,
  `isProbabilityMeasure_pathP`, `pathH_isHermitian` (namespace `RBM.Path`), `PrecGrid`,
  `precGrid_of_le` (namespace `RBM.Gauss.Sizes`).
* The proofs of the two pins, `transferLaw : TransferLaw sz` and `indepIncr : IndepIncr sz`, ported
  from `RBM2D/Path/Walk.lean` at `c9a24cf` (rule R1 of `docs/reports/T2002-prove.md` (b.9):
  `d : Sizes` becomes `sz : Sizes d`; `d` enters only through `Sizes`).  The proof is coordinatewise
  on `Sizes.SeqCoord sz`: at each coordinate the walk is a centred Gaussian of variance
  `(s + kΔ) · seqGvar` (variances of independent centred Gaussians add).
* `GridTransferPT` and `gridTransferPT` ported from `RBM2D/Path/Transfer.lean` at `c9a24cf`,
  lines 1–150, with RBM2D's `Gsig`/`gloop`/`blockMat` on `BlockIndex` replaced by the merged MD-3
  objects `Gres` (`Gt`), `loopFine` (`Lloop`) and `blockMat` on `Idx` (`RBM3D/Loop/GLoopFlow.lean`).
  The error-matrix measurability lemmas (RBM2D lines 155–212) belong to the ST tickets.
-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter Matrix
open scoped NNReal ENNReal

/-! ## 8. The flow carrier: the grid Gaussian walk (DECISIONS §7) -/

namespace RBM.Path

open RBM.Gauss

variable {d : ℕ} (sz : Sizes d)

/-- One independent full draw of the sequence-level Gaussian sample per grid step: the carrier of
`(MBM)` (`1_2:686`) on which the paper's stopping times (`Sol_CalL`, `3_5:134`; `lem:DIfREP`,
`3_5:218`; `eq:def2_stopping`, `3_5:533`) are taken.  `RBM2D/Path/Walk.lean:44`. -/
abbrev PathΩ : Type := ℕ → Sizes.SeqΩ sz

/-- The grid measure: independent copies of `seqP sz`, one per grid step (the independent increments
of `(MBM)`, `1_2:686`).  `RBM2D/Path/Walk.lean:47`. -/
def pathP : Measure (PathΩ sz) := Measure.infinitePi fun _ : ℕ => Sizes.seqP sz

/-- The coordinate filtration (the filtration of `(MBM)`, `1_2:686`): `filt sz k` is generated by
the draws `0, …, k`.  `RBM2D/Path/Walk.lean:50`. -/
def filt : Filtration ℕ (inferInstance : MeasurableSpace (PathΩ sz)) :=
  MeasureTheory.Filtration.piLE

/-- Grid spacing `Δ = (t - s)/K` at size index `n` (flow times of `(MBM)`, `1_2:686`;
`RBM2D/Path/Walk.lean:54`). -/
def gridStep (s t : ℕ → ℝ) (K : ℕ → ℕ) (n : ℕ) : ℝ := (t n - s n) / K n

/-- Grid time `u_k = s + kΔ` (flow times of `(MBM)`, `1_2:686`; `RBM2D/Path/Walk.lean:57`). -/
def gridTime (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) : ℝ := s n + k * gridStep s t K n

/-- The grid walk `H_{u_k} = √s X_0 + √Δ Σ_{i=1}^k X_i` at size index `n` (matrix Brownian motion
`(MBM)`, `1_2:686`, with `H_0 = 0`; for the block Anderson model add `ilambda_0 Ψ` and use
`sz.withLam 0`).  `RBM2D/Path/Walk.lean:60`. -/
def pathH (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (ω : PathΩ sz) :
    Matrix (Idx d (sz.L n) (sz.W n)) (Idx d (sz.L n) (sz.W n)) ℂ :=
  (Real.sqrt (s n) : ℂ) • Sizes.seqXmat sz n (ω 0)
    + (Real.sqrt (gridStep s t K n) : ℂ) • ∑ i ∈ Finset.Icc 1 k, Sizes.seqXmat sz n (ω i)

/-- **Pin (transfer law)**: each grid time has the law of the single-time model at that time
(`(MBM)`, `1_2:686`: `H_u` has the law of `√u X`; `RBM2D/Path/Walk.lean:67`; RBM1D `map_H_eq`).
Proved by the MD tickets, not here. -/
def TransferLaw : Prop :=
  ∀ (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ), 0 ≤ s n → s n ≤ t n → K n ≠ 0 →
    (pathP sz).map (pathH sz s t K n k) =
      (Sizes.seqP sz).map (Sizes.seqHflow sz n (gridTime s t K n k))

/-- **Pin (independent increments)**: the draw `k + 1` is independent of `filt sz k`
(`(MBM)`, `1_2:686`: independent increments; `RBM2D/Path/Walk.lean:74`). -/
def IndepIncr : Prop :=
  ∀ k : ℕ, Indep (filt sz k)
    (MeasurableSpace.comap (fun ω : PathΩ sz => ω (k + 1)) inferInstance) (pathP sz)

instance isProbabilityMeasure_pathP : IsProbabilityMeasure (pathP sz) := by
  unfold pathP; infer_instance

/-- The grid walk is Hermitian at every grid time and sample point. -/
theorem pathH_isHermitian (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (ω : PathΩ sz) :
    (pathH sz s t K n k ω).IsHermitian := by
  unfold pathH
  refine IsHermitian.add ?_ ?_
  · unfold IsHermitian
    rw [conjTranspose_smul, (Sizes.seqXmat_isHermitian sz n (ω 0)).eq,
      show star (Real.sqrt (s n) : ℂ) = (Real.sqrt (s n) : ℂ) from Complex.conj_ofReal _]
  · unfold IsHermitian
    rw [conjTranspose_smul, conjTranspose_sum,
      show star (Real.sqrt (gridStep s t K n) : ℂ) = (Real.sqrt (gridStep s t K n) : ℂ) from
        Complex.conj_ofReal _]
    congr 1
    refine Finset.sum_congr rfl fun i _ => ?_
    exact (Sizes.seqXmat_isHermitian sz n (ω i)).eq

end RBM.Path

namespace RBM.Gauss.Sizes

variable {d : ℕ} (sz : Sizes d) {U : ℕ → Type*}

/-- **`≺` on the grid carrier** (`(stoch_domination)`, `1_2:227–231`; statements at the paper's
stopping times: `Sol_CalL`, `3_5:134`; `lem:DIfREP`, `3_5:218`; `eq:def2_stopping`, `3_5:533`):
`StochDomAt` for `pathP sz` at the *same* scale `sz.size` as `Prec`.  There is no second scale on
the chain. -/
def PrecGrid (ξ ζ : ∀ n, U n → Path.PathΩ sz → ℝ) : Prop :=
  StochDomAt (Path.pathP sz) sz.size ξ ζ

/-- Deterministic domination implies `≺` on the grid carrier. -/
theorem precGrid_of_le {ξ ζ : ∀ n, U n → Path.PathΩ sz → ℝ} (hζ : ∀ n u ω, 0 ≤ ζ n u ω)
    (hle : ∀ n u ω, ξ n u ω ≤ ζ n u ω) : sz.PrecGrid ξ ζ := by
  intro τ hτ D _
  refine Eventually.of_forall fun n => ?_
  have h1 : (1 : ℝ) ≤ ((sz.size n : ℕ) : ℝ) ^ τ :=
    Real.one_le_rpow (by exact_mod_cast sz.one_le_size n) hτ.le
  have hempty : badSetAt (sz.size) ξ ζ τ n = ∅ := by
    ext ω
    simp only [badSetAt, Set.mem_ofPred_eq, Set.mem_empty_iff_false, iff_false, not_exists, not_lt]
    intro u
    nlinarith [hle n u ω, hζ n u ω]
  rw [hempty, measure_empty]
  exact zero_le

end RBM.Gauss.Sizes

/-! ## The proofs of the two pins: port of `RBM2D/Path/Walk.lean` at `c9a24cf`

Rule R1: `d : Sizes` becomes `sz : Sizes d`; `Idx (d.L n) (d.W n)` becomes
`Idx d (sz.L n) (sz.W n)`.  RBM2D line numbers are those of `c9a24cf:RBM2D/Path/Walk.lean`:
`gridTime_last` 85, `measurable_pathH` 127, `pathH_adapted` 142, `indep_incr` 170, `map_incr` 209,
`indepIncr` 214, the Gaussian-sum lemmas 267 and 303, `map_pathH_eq` 541, `transferLaw` 580.
RBM2D's `pathH_isHermitian` (95) is not ported: the pinned probe text above carries its own
proof. -/

namespace RBM.Path

open RBM.Gauss

variable {d : ℕ} (sz : Sizes d)


/-- The last grid time is `t` (RBM1D `time_last`, `GridPath.lean:55`). -/
theorem gridTime_last (s t : ℕ → ℝ) (K : ℕ → ℕ) (n : ℕ) (hK : K n ≠ 0) :
    gridTime s t K n (K n) = t n := by
  have hK' : (K n : ℝ) ≠ 0 := Nat.cast_ne_zero.2 hK
  unfold gridTime gridStep
  rw [mul_div_cancel₀ _ hK']
  ring

/-- Entries of `Sizes.seqXmat sz n` are measurable (the merged `measurable_Xentry` composed with
`measurable_slice`; RBM1D reads the entries directly). -/
private lemma measurable_seqXentry (n : ℕ) (i j : Idx d (sz.L n) (sz.W n)) :
    Measurable fun ω : Sizes.SeqΩ sz => Sizes.seqXmat sz n ω i j :=
  (measurable_Xentry d (sz.L n) (sz.W n) i j).comp (Sizes.measurable_slice sz n)

/-- Entrywise formula for the walk. -/
private lemma pathH_apply (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ)
    (i j : Idx d (sz.L n) (sz.W n)) (ω : PathΩ sz) :
    pathH sz s t K n k ω i j
      = (Real.sqrt (s n) : ℂ) * Sizes.seqXmat sz n (ω 0) i j
        + (Real.sqrt (gridStep s t K n) : ℂ)
          * ∑ l ∈ Finset.Icc 1 k, Sizes.seqXmat sz n (ω l) i j := by
  simp [pathH, Matrix.add_apply, Matrix.smul_apply, Matrix.sum_apply, Finset.mul_sum]

/-- (RBM1D `measurable_H`, `GridPath.lean:83`; entrywise.) -/
theorem measurable_pathH (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (i j : Idx d (sz.L n) (sz.W n)) :
    Measurable fun ω : PathΩ sz => pathH sz s t K n k ω i j := by
  have heq : (fun ω : PathΩ sz => pathH sz s t K n k ω i j) =
      fun ω => (Real.sqrt (s n) : ℂ) * Sizes.seqXmat sz n (ω 0) i j
        + (Real.sqrt (gridStep s t K n) : ℂ)
          * ∑ l ∈ Finset.Icc 1 k, Sizes.seqXmat sz n (ω l) i j :=
    funext fun ω => pathH_apply sz s t K n k i j ω
  rw [heq]
  apply Measurable.add
  · exact ((measurable_seqXentry sz n i j).comp (measurable_pi_apply 0)).const_mul _
  · apply Measurable.const_mul
    exact Finset.measurable_sum _ fun l _ =>
      (measurable_seqXentry sz n i j).comp (measurable_pi_apply l)

/-- (RBM1D `H_adapted`, `GridPath.lean:103`.) -/
theorem pathH_adapted (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (i j : Idx d (sz.L n) (sz.W n)) :
    StronglyMeasurable[filt sz k] (fun ω : PathΩ sz => pathH sz s t K n k ω i j) := by
  rw [stronglyMeasurable_iff_measurable]
  have heq : (fun ω : PathΩ sz => pathH sz s t K n k ω i j) =
      fun ω => (Real.sqrt (s n) : ℂ) * Sizes.seqXmat sz n (ω 0) i j
        + (Real.sqrt (gridStep s t K n) : ℂ)
          * ∑ l ∈ Finset.Icc 1 k, Sizes.seqXmat sz n (ω l) i j :=
    funext fun ω => pathH_apply sz s t K n k i j ω
  rw [heq]
  have hmeas : ∀ l : ℕ, l ≤ k → Measurable[filt sz k] (fun ω : PathΩ sz => ω l) := by
    intro l hl
    have : (fun ω : PathΩ sz => ω l)
        = (fun g : Set.Iic k → Sizes.SeqΩ sz => g ⟨l, hl⟩)
          ∘ (Preorder.restrictLe (π := fun _ : ℕ => Sizes.SeqΩ sz) k) := rfl
    rw [this]
    exact (measurable_pi_apply (⟨l, hl⟩ : Set.Iic k)).comp
      (comap_measurable (Preorder.restrictLe (π := fun _ : ℕ => Sizes.SeqΩ sz) k))
  apply Measurable.add
  · exact ((measurable_seqXentry sz n i j).comp (hmeas 0 (by omega))).const_mul _
  · apply Measurable.const_mul
    exact Finset.measurable_sum _ fun l hl =>
      (measurable_seqXentry sz n i j).comp
        (hmeas l (by simp only [Finset.mem_Icc] at hl; omega))

/-! ### Increment independence and law -/

/-- The `k`-th increment `ω ↦ ω (k+1)` is independent of the coordinate filtration `filt sz k`
(RBM1D `indep_incr`, `GridPath.lean:128`; the argument order is RBM1D's, increment first). -/
theorem indep_incr (k : ℕ) :
    Indep (MeasurableSpace.comap (fun ω : PathΩ sz => ω (k + 1)) inferInstance) (filt sz k)
      (pathP sz) := by
  have hI : iIndepFun (fun i : ℕ => (fun ω : PathΩ sz => ω i)) (pathP sz) :=
    iIndepFun_infinitePi (X := fun _ : ℕ => (id : Sizes.SeqΩ sz → Sizes.SeqΩ sz))
      (mX := fun _ => measurable_id)
  have hIndep : iIndep
      (fun n : ℕ => MeasurableSpace.comap (fun ω : PathΩ sz => ω n) inferInstance)
      (pathP sz) := (iIndepFun_iff_iIndep
        (fun _ : ℕ => (inferInstance : MeasurableSpace (Sizes.SeqΩ sz)))
        (fun i ω => ω i) (pathP sz)).mp hI
  have hle : ∀ n : ℕ, MeasurableSpace.comap (fun ω : PathΩ sz => ω n) inferInstance
      ≤ (inferInstance : MeasurableSpace (PathΩ sz)) :=
    fun n => le_iSup (fun n => MeasurableSpace.comap (fun ω : PathΩ sz => ω n) inferInstance) n
  have hsplit := indep_biSup_compl hle hIndep (Set.Iic k)
  have hfilt : filt sz k
      = ⨆ n ∈ Set.Iic k, MeasurableSpace.comap (fun ω : PathΩ sz => ω n) inferInstance := by
    have hshow : filt sz k =
        (inferInstance : MeasurableSpace (↥(Set.Iic k) → Sizes.SeqΩ sz)).comap
          (Preorder.restrictLe (π := fun _ : ℕ => Sizes.SeqΩ sz) k) := rfl
    have hpi : (inferInstance : MeasurableSpace (↥(Set.Iic k) → Sizes.SeqΩ sz))
        = ⨆ a : ↥(Set.Iic k),
            MeasurableSpace.comap (fun g : ↥(Set.Iic k) → Sizes.SeqΩ sz => g a) inferInstance :=
      rfl
    rw [hshow, hpi, MeasurableSpace.comap_iSup, iSup_subtype]
    simp only [MeasurableSpace.comap_comp]
    apply iSup_congr
    intro i
    apply iSup_congr
    intro _
    rfl
  rw [hfilt]
  have hmono : MeasurableSpace.comap (fun ω : PathΩ sz => ω (k + 1)) inferInstance
      ≤ ⨆ n ∈ (Set.Iic k)ᶜ, MeasurableSpace.comap (fun ω : PathΩ sz => ω n) inferInstance := by
    have hmem : (k + 1) ∈ (Set.Iic k)ᶜ := by simp
    exact le_biSup (fun n => MeasurableSpace.comap (fun ω : PathΩ sz => ω n) inferInstance) hmem
  exact indep_of_indep_of_le_left hsplit.symm hmono

/-- The law of a single increment is `Sizes.seqP sz` (RBM1D `map_incr`, `GridPath.lean:162`). -/
theorem map_incr (k : ℕ) :
    (pathP sz).map (fun ω : PathΩ sz => ω (k + 1)) = Sizes.seqP sz :=
  MeasureTheory.Measure.infinitePi_map_eval _ (k + 1)

/-- **Pinned theorem (independent increments).** -/
theorem indepIncr : IndepIncr sz := fun k => (indep_incr sz k).symm

/-! ### The transfer law

`pathH` collapses to `Sizes.seqXmat sz n` evaluated at a real-linear combination of the raw
draws; the law of this combination is computed coordinatewise. -/

section AlgebraicIdentities

variable {sz}

private lemma slice_add (n : ℕ) (ω ν : Sizes.SeqΩ sz) :
    Sizes.slice sz n (ω + ν) = Sizes.slice sz n ω + Sizes.slice sz n ν := rfl

private lemma slice_smul (n : ℕ) (a : ℝ) (ω : Sizes.SeqΩ sz) :
    Sizes.slice sz n (a • ω) = a • Sizes.slice sz n ω := rfl

private lemma slice_sum {ι : Type*} (n : ℕ) (S : Finset ι) (ω : ι → Sizes.SeqΩ sz) :
    Sizes.slice sz n (∑ l ∈ S, ω l) = ∑ l ∈ S, Sizes.slice sz n (ω l) := by
  funext c
  simp [Sizes.slice, Finset.sum_apply]

/-- Replaces RBM1D `Xentry_add` (`GridPath.lean:175`): the extra `slice` layer of RBM2D. -/
private lemma seqXmat_add (n : ℕ) (ω ν : Sizes.SeqΩ sz) :
    Sizes.seqXmat sz n (ω + ν) = Sizes.seqXmat sz n ω + Sizes.seqXmat sz n ν := by
  unfold Sizes.seqXmat
  rw [slice_add, Xmat_add]

/-- Replaces RBM1D `Xentry_smul` (`GridPath.lean:180`). -/
private lemma seqXmat_smul (n : ℕ) (a : ℝ) (ω : Sizes.SeqΩ sz) :
    Sizes.seqXmat sz n (a • ω) = a • Sizes.seqXmat sz n ω := by
  unfold Sizes.seqXmat
  rw [slice_smul, Xmat_smul]

/-- Replaces RBM1D `Xentry_sum` (`GridPath.lean:189`). -/
private lemma seqXmat_sum {ι : Type*} (n : ℕ) (S : Finset ι) (ω : ι → Sizes.SeqΩ sz) :
    Sizes.seqXmat sz n (∑ l ∈ S, ω l) = ∑ l ∈ S, Sizes.seqXmat sz n (ω l) := by
  unfold Sizes.seqXmat
  rw [slice_sum]
  exact map_sum (Xlinear d (sz.L n) (sz.W n)) (fun l => Sizes.slice sz n (ω l)) S

/-- Real scalars act on complex matrices through their coercion. -/
private lemma real_smul_matrix' {m : Type*} (r : ℝ) (M : Matrix m m ℂ) :
    r • M = (r : ℂ) • M := by
  ext i j
  simp [Complex.real_smul]

end AlgebraicIdentities

section OneDimensionalGaussianSum

/-- **The Icc-sum of an iid centred Gaussian family is Gaussian with added variance.** A pure
probability fact (RBM1D `sumIcc_map_gaussianReal`, `GridPath.lean:202`). -/
private lemma sumIcc_map_gaussianReal {Ω' : Type*} [MeasurableSpace Ω'] {μ' : Measure Ω'}
    [IsProbabilityMeasure μ'] {Y : ℕ → Ω' → ℝ} (hYm : ∀ i, Measurable (Y i))
    (hY : iIndepFun Y μ') {w : ℝ≥0} (hYd : ∀ i, μ'.map (Y i) = gaussianReal 0 w) (k : ℕ) :
    μ'.map (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) = gaussianReal 0 (k • w) := by
  induction k with
  | zero =>
      have hEmpty : Finset.Icc 1 0 = (∅ : Finset ℕ) := Finset.Icc_eq_empty (by omega)
      simp only [hEmpty, Finset.sum_empty]
      rw [Measure.map_const, measure_univ, one_smul, zero_smul, gaussianReal_zero_var]
  | succ k ih =>
      have hnotmem : (k + 1) ∉ Finset.Icc 1 k := by simp
      have hins : Finset.Icc 1 (k + 1) = insert (k + 1) (Finset.Icc 1 k) := by
        ext i; simp only [Finset.mem_Icc, Finset.mem_insert]; omega
      have hfun : (fun ω => ∑ i ∈ Finset.Icc 1 (k + 1), Y i ω)
          = (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) + Y (k + 1) := by
        funext ω
        rw [hins, Finset.sum_insert hnotmem, add_comm]
        rfl
      rw [hfun]
      have hsummeas : Measurable (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) :=
        Finset.measurable_sum _ fun i _ => hYm i
      have hlaw1 : HasLaw (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) (gaussianReal 0 (k • w)) μ' :=
        ⟨hsummeas.aemeasurable, ih⟩
      have hlaw2 : HasLaw (Y (k + 1)) (gaussianReal 0 w) μ' :=
        ⟨(hYm (k + 1)).aemeasurable, hYd (k + 1)⟩
      have hindep : IndepFun (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) (Y (k + 1)) μ' := by
        have h := hY.indepFun_finsetSum_of_notMem hYm hnotmem
        have heq : (∑ j ∈ Finset.Icc 1 k, Y j) = fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω := by
          funext ω; simp [Finset.sum_apply]
        rwa [heq] at h
      have hres := gaussianReal_add_gaussianReal_of_indepFun hindep hlaw1 hlaw2
      rw [hres, add_zero, ← succ_nsmul]

/-- **The two-scale weighted sum lemma** (RBM1D `weightedSum_map_gaussianReal`,
`GridPath.lean:239`).  With `a` scaling the base draw `Y 0` and `b` scaling each of the `k`
increments `Y 1, …, Y k`, the total variance is `a² w + k (b² w)`. -/
private lemma weightedSum_map_gaussianReal {Ω' : Type*} [MeasurableSpace Ω'] {μ' : Measure Ω'}
    [IsProbabilityMeasure μ'] {Y : ℕ → Ω' → ℝ} (hYm : ∀ i, Measurable (Y i))
    (hY : iIndepFun Y μ') {w : ℝ≥0} (hYd : ∀ i, μ'.map (Y i) = gaussianReal 0 w)
    (a b : ℝ) (k : ℕ) :
    μ'.map (fun ω => a * Y 0 ω + b * ∑ i ∈ Finset.Icc 1 k, Y i ω)
      = gaussianReal 0
          (NNReal.mk (a ^ 2) (sq_nonneg a) * w + k • (NNReal.mk (b ^ 2) (sq_nonneg b) * w)) := by
  classical
  have hindep : IndepFun (fun ω => a * Y 0 ω) (fun ω => b * ∑ i ∈ Finset.Icc 1 k, Y i ω) μ' := by
    have h0 : IndepFun (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) (Y 0) μ' := by
      have h := hY.indepFun_finsetSum_of_notMem hYm (s := Finset.Icc 1 k) (i := 0) (by simp)
      have heq : (∑ j ∈ Finset.Icc 1 k, Y j) = fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω := by
        funext ω; simp [Finset.sum_apply]
      rwa [heq] at h
    exact h0.symm.comp (φ := (a * ·)) (ψ := (b * ·)) (by fun_prop) (by fun_prop)
  have hlaw0 : HasLaw (fun ω => a * Y 0 ω)
      (gaussianReal 0 (NNReal.mk (a ^ 2) (sq_nonneg a) * w)) μ' := by
    refine ⟨by fun_prop, ?_⟩
    have : (fun ω => a * Y 0 ω) = (a * ·) ∘ Y 0 := rfl
    rw [this, ← Measure.map_map (by fun_prop) (hYm 0), hYd 0, gaussianReal_map_const_mul,
      mul_zero]
  have hsummeas : Measurable (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) :=
    Finset.measurable_sum _ fun i _ => hYm i
  have hlawsum : μ'.map (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) = gaussianReal 0 (k • w) :=
    sumIcc_map_gaussianReal hYm hY hYd k
  have hlaw1 : HasLaw (fun ω => b * ∑ i ∈ Finset.Icc 1 k, Y i ω)
      (gaussianReal 0 (NNReal.mk (b ^ 2) (sq_nonneg b) * (k • w))) μ' := by
    refine ⟨by fun_prop, ?_⟩
    have heq : (fun ω => b * ∑ i ∈ Finset.Icc 1 k, Y i ω)
        = (b * ·) ∘ (fun ω => ∑ i ∈ Finset.Icc 1 k, Y i ω) := rfl
    rw [heq, ← Measure.map_map (by fun_prop) hsummeas, hlawsum, gaussianReal_map_const_mul,
      mul_zero]
  have hgoal_eq : (fun ω => a * Y 0 ω + b * ∑ i ∈ Finset.Icc 1 k, Y i ω)
      = (fun ω => a * Y 0 ω) + fun ω => b * ∑ i ∈ Finset.Icc 1 k, Y i ω := rfl
  rw [hgoal_eq]
  have hres := gaussianReal_add_gaussianReal_of_indepFun hindep hlaw0 hlaw1
  rw [hres, add_zero]
  congr 1
  rw [nsmul_eq_mul, nsmul_eq_mul]
  apply NNReal.coe_injective
  push_cast
  ring

end OneDimensionalGaussianSum

section CombinedIdentities

variable {sz}

/-- `pathH` collapses to `seqXmat` evaluated at the real-linear grid combination of the raw
draws (RBM1D `H_eq_Xmat_combined`, `GridPath.lean:295`).  Uses `seqXmat_add`, `seqXmat_smul`,
`seqXmat_sum` above. -/
private lemma pathH_eq_seqXmat_combined (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (ω : PathΩ sz) :
    pathH sz s t K n k ω
      = Sizes.seqXmat sz n ((Real.sqrt (s n) : ℝ) • ω 0
          + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i) := by
  rw [seqXmat_add, seqXmat_smul, seqXmat_smul, seqXmat_sum, real_smul_matrix',
    real_smul_matrix']
  rfl

/-- `seqHflow` collapses to `seqXmat` evaluated at the real scaling `√u • ω'` (RBM1D
`Hflow_eq_Xmat_smul`, `GridPath.lean:304`; from `Sizes.seqHflow_eq_smul` and `seqXmat_smul`). -/
private lemma seqHflow_eq_seqXmat_smul (n : ℕ) (u : ℝ) (ω' : Sizes.SeqΩ sz) :
    Sizes.seqHflow sz n u ω' = Sizes.seqXmat sz n ((Real.sqrt u : ℝ) • ω') := by
  rw [Sizes.seqHflow_eq_smul, seqXmat_smul, real_smul_matrix']

private lemma measurable_seqXmat (n : ℕ) : Measurable (Sizes.seqXmat sz n) :=
  measurable_pi_iff.2 fun i => measurable_pi_iff.2 fun j => measurable_seqXentry sz n i j

private lemma measurable_combined (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) :
    Measurable (fun ω : PathΩ sz => (Real.sqrt (s n) : ℝ) • ω 0
      + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i) := by
  have h1 : Measurable (fun ω : PathΩ sz => ω 0) := measurable_pi_apply 0
  have h2 : Measurable (fun ω : PathΩ sz => ∑ i ∈ Finset.Icc 1 k, ω i) :=
    Finset.measurable_sum _ fun i _ => measurable_pi_apply i
  exact (h1.const_smul (Real.sqrt (s n))).add (h2.const_smul (Real.sqrt (gridStep s t K n)))

private lemma measurable_smul_SeqΩ (u : ℝ) :
    Measurable (fun ω' : Sizes.SeqΩ sz => (Real.sqrt u : ℝ) • ω') :=
  measurable_id.const_smul (Real.sqrt u)

end CombinedIdentities

section TheTransferLemma

variable {sz}

/-- **The column law.** At a fixed raw coordinate `c`, the `k+1`-fold grid combination of iid
copies of `gaussianReal 0 (seqGvar sz c)` is Gaussian with the added variance (RBM1D
`map_column_eq`, `GridPath.lean:331`). -/
private lemma map_column_eq (c : Sizes.SeqCoord sz) (a b : ℝ) (k : ℕ) :
    (Measure.infinitePi (fun _ : ℕ => gaussianReal 0 (Sizes.seqGvar sz c))).map
        (fun y : ℕ → ℝ => a * y 0 + b * ∑ i ∈ Finset.Icc 1 k, y i)
      = gaussianReal 0 (NNReal.mk (a ^ 2) (sq_nonneg a) * Sizes.seqGvar sz c
          + k • (NNReal.mk (b ^ 2) (sq_nonneg b) * Sizes.seqGvar sz c)) := by
  have hY : iIndepFun (fun i : ℕ => (fun y : ℕ → ℝ => y i))
      (Measure.infinitePi (fun _ : ℕ => gaussianReal 0 (Sizes.seqGvar sz c))) :=
    iIndepFun_infinitePi (X := fun _ : ℕ => (id : ℝ → ℝ)) (mX := fun _ => measurable_id)
  have hYm : ∀ i : ℕ, Measurable (fun y : ℕ → ℝ => y i) := fun i => measurable_pi_apply i
  have hYd : ∀ i : ℕ, (Measure.infinitePi (fun _ : ℕ => gaussianReal 0 (Sizes.seqGvar sz c))).map
      (fun y : ℕ → ℝ => y i) = gaussianReal 0 (Sizes.seqGvar sz c) :=
    fun i => Measure.infinitePi_map_eval _ i
  exact weightedSum_map_gaussianReal hYm hY hYd a b k

/-- The nested product over `SeqCoord sz` first, then over the grid index `ℕ` (RBM1D `Pg'`). -/
private def pathP' {d : ℕ} (sz : Sizes d) : Measure (Sizes.SeqCoord sz → ℕ → ℝ) :=
  Measure.infinitePi
    (fun c : Sizes.SeqCoord sz =>
      Measure.infinitePi (fun _ : ℕ => gaussianReal 0 (Sizes.seqGvar sz c)))

/-- The composite reindexing map `(SeqCoord sz → ℕ → ℝ) → PathΩ sz`: uncurry, swap the two axes,
curry back (RBM1D `swapEquiv`, `GridPath.lean:350`). -/
private def swapEquiv {d : ℕ} (sz : Sizes d) : (Sizes.SeqCoord sz → ℕ → ℝ) → PathΩ sz :=
  (MeasurableEquiv.curry ℕ (Sizes.SeqCoord sz) ℝ) ∘
    (MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord sz => ℝ)
      (Equiv.prodComm (Sizes.SeqCoord sz) ℕ)) ∘
    (MeasurableEquiv.curry (Sizes.SeqCoord sz) ℕ ℝ).symm

private lemma measurable_swapEquiv : Measurable (swapEquiv sz) :=
  (MeasurableEquiv.curry ℕ (Sizes.SeqCoord sz) ℝ).measurable.comp
    ((MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord sz => ℝ)
        (Equiv.prodComm (Sizes.SeqCoord sz) ℕ)).measurable.comp
      (MeasurableEquiv.curry (Sizes.SeqCoord sz) ℕ ℝ).symm.measurable)

/-- **The swap identity** (RBM1D `Pg_swap_eq`, `GridPath.lean:364`).  `pathP' sz`, after
reordering the two axes, coincides with `pathP sz`.  Chain of `Measure.infinitePi_map_curry_symm`,
`Measure.infinitePi_map_piCongrLeft` and `Measure.infinitePi_map_curry`. -/
private lemma pathP_swap_eq : (pathP' sz).map (swapEquiv sz) = pathP sz := by
  have ha : (pathP' sz).map ((MeasurableEquiv.curry (Sizes.SeqCoord sz) ℕ ℝ).symm)
      = Measure.infinitePi
          (fun p : Sizes.SeqCoord sz × ℕ => gaussianReal 0 (Sizes.seqGvar sz p.1)) :=
    Measure.infinitePi_map_curry_symm
      (μ := fun (c : Sizes.SeqCoord sz) (_ : ℕ) => gaussianReal 0 (Sizes.seqGvar sz c))
  have hb : (Measure.infinitePi
        (fun p : Sizes.SeqCoord sz × ℕ => gaussianReal 0 (Sizes.seqGvar sz p.1))).map
      (MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord sz => ℝ)
        (Equiv.prodComm (Sizes.SeqCoord sz) ℕ))
      = Measure.infinitePi
          (fun p : ℕ × Sizes.SeqCoord sz => gaussianReal 0 (Sizes.seqGvar sz p.2)) :=
    Measure.infinitePi_map_piCongrLeft
      (μ := fun p : ℕ × Sizes.SeqCoord sz => gaussianReal 0 (Sizes.seqGvar sz p.2))
      (Equiv.prodComm (Sizes.SeqCoord sz) ℕ)
  have hc : (Measure.infinitePi
        (fun p : ℕ × Sizes.SeqCoord sz => gaussianReal 0 (Sizes.seqGvar sz p.2))).map
      (MeasurableEquiv.curry ℕ (Sizes.SeqCoord sz) ℝ) = pathP sz :=
    Measure.infinitePi_map_curry
      (μ := fun (_ : ℕ) (c : Sizes.SeqCoord sz) => gaussianReal 0 (Sizes.seqGvar sz c))
  change (pathP' sz).map ((MeasurableEquiv.curry ℕ (Sizes.SeqCoord sz) ℝ) ∘
      (MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord sz => ℝ)
        (Equiv.prodComm (Sizes.SeqCoord sz) ℕ)) ∘
      (MeasurableEquiv.curry (Sizes.SeqCoord sz) ℕ ℝ).symm) = pathP sz
  rw [← Measure.map_map (by fun_prop) (by fun_prop), ← Measure.map_map (by fun_prop) (by fun_prop),
    ha, hb, hc]

/-- The pointwise formula for the swap map (RBM1D `swapEquiv_apply`, `GridPath.lean:384`). -/
private lemma swapEquiv_apply (X : Sizes.SeqCoord sz → ℕ → ℝ) (i : ℕ) (c : Sizes.SeqCoord sz) :
    swapEquiv sz X i c = X c i := by
  change (MeasurableEquiv.curry ℕ (Sizes.SeqCoord sz) ℝ)
      ((MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord sz => ℝ)
          (Equiv.prodComm (Sizes.SeqCoord sz) ℕ))
        ((MeasurableEquiv.curry (Sizes.SeqCoord sz) ℕ ℝ).symm X)) i c = X c i
  rw [MeasurableEquiv.coe_curry]
  change (MeasurableEquiv.piCongrLeft (fun _ : ℕ × Sizes.SeqCoord sz => ℝ)
      (Equiv.prodComm (Sizes.SeqCoord sz) ℕ))
      ((MeasurableEquiv.curry (Sizes.SeqCoord sz) ℕ ℝ).symm X) (i, c) = X c i
  have key := MeasurableEquiv.piCongrLeft_apply_apply (Equiv.prodComm (Sizes.SeqCoord sz) ℕ)
    (β := fun _ : ℕ × Sizes.SeqCoord sz => ℝ)
    ((MeasurableEquiv.curry (Sizes.SeqCoord sz) ℕ ℝ).symm X) (c, i)
  rw [show Equiv.prodComm (Sizes.SeqCoord sz) ℕ (c, i) = (i, c) from rfl] at key
  rw [key, MeasurableEquiv.coe_curry_symm]
  rfl

/-- **The combined-grid law** (RBM1D `map_combined_eq`, `GridPath.lean:400`).  The `k+1`-fold
grid combination has, at each raw coordinate `c : SeqCoord sz`, the Gaussian law of the sum of the
variances contributed by the base draw and by the `k` increments. -/
private lemma map_combined_eq (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) :
    (pathP sz).map (fun ω : PathΩ sz => (Real.sqrt (s n) : ℝ) • ω 0
        + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i)
      = Measure.infinitePi (fun c : Sizes.SeqCoord sz => gaussianReal 0
          (NNReal.mk (Real.sqrt (s n) ^ 2) (sq_nonneg _) * Sizes.seqGvar sz c
            + k • (NNReal.mk (Real.sqrt (gridStep s t K n) ^ 2) (sq_nonneg _)
              * Sizes.seqGvar sz c))) := by
  have hcomp : (fun ω : PathΩ sz => (Real.sqrt (s n) : ℝ) • ω 0
        + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i) ∘ (swapEquiv sz)
      = (fun X : Sizes.SeqCoord sz → ℕ → ℝ => fun c => Real.sqrt (s n) * X c 0
          + Real.sqrt (gridStep s t K n) * ∑ i ∈ Finset.Icc 1 k, X c i) := by
    funext X
    funext c
    simp only [Function.comp_apply, Pi.add_apply, Pi.smul_apply, smul_eq_mul, Finset.sum_apply,
      swapEquiv_apply]
  rw [← pathP_swap_eq, Measure.map_map (measurable_combined s t K n k) measurable_swapEquiv,
    hcomp]
  have hfmeas : ∀ c : Sizes.SeqCoord sz, Measurable (fun y : ℕ → ℝ => Real.sqrt (s n) * y 0
      + Real.sqrt (gridStep s t K n) * ∑ i ∈ Finset.Icc 1 k, y i) := fun c => by
    have h1 : Measurable (fun y : ℕ → ℝ => y 0) := measurable_pi_apply 0
    have h2 : Measurable (fun y : ℕ → ℝ => ∑ i ∈ Finset.Icc 1 k, y i) :=
      Finset.measurable_sum _ fun i _ => measurable_pi_apply i
    exact (h1.const_mul _).add (h2.const_mul _)
  have hpi := Measure.infinitePi_map_pi
      (μ := fun c : Sizes.SeqCoord sz =>
        Measure.infinitePi (fun _ : ℕ => gaussianReal 0 (Sizes.seqGvar sz c)))
      (f := fun c : Sizes.SeqCoord sz => fun y : ℕ → ℝ => Real.sqrt (s n) * y 0
        + Real.sqrt (gridStep s t K n) * ∑ i ∈ Finset.Icc 1 k, y i) hfmeas
  rw [pathP']
  exact hpi.trans (congrArg Measure.infinitePi
    (funext fun c => map_column_eq c (Real.sqrt (s n)) (Real.sqrt (gridStep s t K n)) k))

/-- **The scaled-flow law** (RBM1D `map_smul_eq`, `GridPath.lean:431`; the unused size argument
is dropped).  The law of `√u • ω` on the common sample space has, at each coordinate, variance
`u` times the original variance. -/
private lemma map_smul_eq (u : ℝ) (hu : 0 ≤ u) :
    (Sizes.seqP sz).map (fun ω' : Sizes.SeqΩ sz => (Real.sqrt u : ℝ) • ω')
      = Measure.infinitePi
          (fun c : Sizes.SeqCoord sz => gaussianReal 0 (NNReal.mk u hu * Sizes.seqGvar sz c)) := by
  have hfmeas : ∀ c : Sizes.SeqCoord sz, Measurable ((Real.sqrt u : ℝ) * ·) :=
    fun c => by fun_prop
  have h1 : (Sizes.seqP sz).map (fun ω' : Sizes.SeqΩ sz => fun c => (Real.sqrt u : ℝ) * ω' c)
      = Measure.infinitePi
          (fun c : Sizes.SeqCoord sz =>
            (gaussianReal 0 (Sizes.seqGvar sz c)).map ((Real.sqrt u : ℝ) * ·)) :=
    Measure.infinitePi_map_pi
      (μ := fun c : Sizes.SeqCoord sz => gaussianReal 0 (Sizes.seqGvar sz c))
      (f := fun _ : Sizes.SeqCoord sz => ((Real.sqrt u : ℝ) * ·)) hfmeas
  have heq : (fun ω' : Sizes.SeqΩ sz => (Real.sqrt u : ℝ) • ω')
      = (fun ω' : Sizes.SeqΩ sz => fun c => (Real.sqrt u : ℝ) * ω' c) := by
    funext ω' c; simp [smul_eq_mul]
  rw [heq, h1]
  congr 1
  funext c
  rw [gaussianReal_map_const_mul, mul_zero]
  congr 1
  apply NNReal.coe_injective
  push_cast
  rw [Real.sq_sqrt hu]

end TheTransferLemma

/-- **The transfer lemma** (RBM1D `map_H_eq`, `GridPath.lean:452`).  The grid walk `pathH` at grid
step `k` has the same law as the one-time flow `Sizes.seqHflow` at the grid time. -/
theorem map_pathH_eq (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) (hs : 0 ≤ s n) (hst : s n ≤ t n)
    (hK : K n ≠ 0) :
    (pathP sz).map (pathH sz s t K n k)
      = (Sizes.seqP sz).map (Sizes.seqHflow sz n (gridTime s t K n k)) := by
  have hstep : 0 ≤ gridStep s t K n := div_nonneg (by linarith) (Nat.cast_nonneg _)
  have hu : 0 ≤ gridTime s t K n k := by
    have : 0 ≤ (k : ℝ) * gridStep s t K n := mul_nonneg (Nat.cast_nonneg k) hstep
    unfold gridTime; linarith
  have hHeq : pathH sz s t K n k = fun ω => Sizes.seqXmat sz n ((Real.sqrt (s n) : ℝ) • ω 0
      + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i) :=
    funext (pathH_eq_seqXmat_combined s t K n k)
  have hHfloweq : Sizes.seqHflow sz n (gridTime s t K n k)
      = fun ω' => Sizes.seqXmat sz n ((Real.sqrt (gridTime s t K n k) : ℝ) • ω') :=
    funext (seqHflow_eq_seqXmat_smul n (gridTime s t K n k))
  rw [hHeq, hHfloweq,
    show (fun ω : PathΩ sz => Sizes.seqXmat sz n ((Real.sqrt (s n) : ℝ) • ω 0
        + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i))
      = Sizes.seqXmat sz n ∘ (fun ω => (Real.sqrt (s n) : ℝ) • ω 0
        + (Real.sqrt (gridStep s t K n) : ℝ) • ∑ i ∈ Finset.Icc 1 k, ω i) from rfl,
    show (fun ω' : Sizes.SeqΩ sz => Sizes.seqXmat sz n ((Real.sqrt (gridTime s t K n k) : ℝ) • ω'))
      = Sizes.seqXmat sz n ∘ (fun ω' => (Real.sqrt (gridTime s t K n k) : ℝ) • ω') from rfl,
    ← Measure.map_map (measurable_seqXmat n) (measurable_combined s t K n k),
    ← Measure.map_map (measurable_seqXmat n) (measurable_smul_SeqΩ (gridTime s t K n k)),
    map_combined_eq s t K n k, map_smul_eq (gridTime s t K n k) hu]
  congr 1
  refine congrArg Measure.infinitePi (funext fun c => ?_)
  have hvar : NNReal.mk (Real.sqrt (s n) ^ 2) (sq_nonneg _) * Sizes.seqGvar sz c
      + k • (NNReal.mk (Real.sqrt (gridStep s t K n) ^ 2) (sq_nonneg _) * Sizes.seqGvar sz c)
      = NNReal.mk (gridTime s t K n k) hu * Sizes.seqGvar sz c := by
    have h1 : Real.sqrt (s n) ^ 2 = s n := Real.sq_sqrt hs
    have h2 : Real.sqrt (gridStep s t K n) ^ 2 = gridStep s t K n := Real.sq_sqrt hstep
    apply NNReal.coe_injective
    push_cast
    rw [h1, h2]
    unfold gridTime
    ring
  rw [hvar]

/-- **Pinned theorem (transfer law).** -/
theorem transferLaw : TransferLaw sz :=
  fun s t K n k hs hst hK => map_pathH_eq sz s t K n k hs hst hK

end RBM.Path

/-! ## The per-time transfer: port of `RBM2D/Path/Transfer.lean` at `c9a24cf`, lines 1–150

`GridTransferPT` is copied with its docstring (RBM2D `Path/Transfer.lean:35`), proved from
`transferLaw` pointwise in `(n, k)` (`RBM2D/Path/Transfer.lean:58`).  Rule R1 as above.  The
measurability helpers (RBM2D lines 84–150) are re-expressed for `Gres` (the resolvent entry; RBM2D
`Gsig`), `blockMat` on `Idx` and `loopFine` (the loop of a flow matrix on the fine lattice; RBM2D
`gloop ∘ blockMat`), the matrix argument being the free variable; their names carry the file stem
(rule (E)). -/

namespace RBM.Path

open RBM.Gauss

variable {d : ℕ} (sz : Sizes d)

/-- **Pin (per-time transfer, grid ↔ single-time model)** for a matrix functional `F`
(measurable in the matrix) and a control `ζ` depending on the time only: the per-time
domination of `F(H_{u_k})` on the walk over all grid indices `k ≤ K_n`, for grids ending at
`t_n`, is equivalent to that of `F(√u X)` on `seqP` over the grid times.  Proof route: the
transfer law, pointwise in `(n, k)`.  `RBM2D/Path/Transfer.lean:35`. -/
def GridTransferPT (s t : ℕ → ℝ) (K : ℕ → ℕ) {V : ℕ → Type}
    (F : ∀ n, V n → ℝ → Matrix (Idx d (sz.L n) (sz.W n)) (Idx d (sz.L n) (sz.W n)) ℂ → ℝ)
    (ζ : ∀ n, V n → ℝ → ℝ) : Prop :=
  (∀ n, 0 ≤ s n) → (∀ n, s n ≤ t n) → (∀ n, K n ≠ 0) →
  (∀ n (v : V n) (u : ℝ), Measurable (F n v u)) →
    (PerTimeDomAt (pathP sz) sz.size (U := fun n => Fin (K n + 1) × V n)
        (fun n p ω => F n p.2 (gridTime s t K n p.1) (pathH sz s t K n p.1 ω))
        (fun n p _ => ζ n p.2 (gridTime s t K n p.1)) ↔
      PerTimeDomAt (Sizes.seqP sz) sz.size (U := fun n => Fin (K n + 1) × V n)
        (fun n p ω => F n p.2 (gridTime s t K n p.1)
          (Sizes.seqHflow sz n (gridTime s t K n p.1) ω))
        (fun n p _ => ζ n p.2 (gridTime s t K n p.1)))

private theorem transfer_measurable_pathH (s t : ℕ → ℝ) (K : ℕ → ℕ) (n k : ℕ) :
    Measurable (pathH sz s t K n k) :=
  Measurable.of_eval_matrix _ fun i j => measurable_pathH sz s t K n k i j

private theorem transfer_measurable_seqHflow (n : ℕ) (u : ℝ) :
    Measurable (Sizes.seqHflow sz n u) :=
  Measurable.of_eval_matrix _ fun i j => Sizes.measurable_seqHflow_entry sz n u i j

/-- **The per-time transfer** between the grid walk and the single-time model (`GridTransferPT`),
from `transferLaw`, pointwise in `(n, k)`.  `RBM2D/Path/Transfer.lean:58`. -/
theorem gridTransferPT (s t : ℕ → ℝ) (K : ℕ → ℕ) {V : ℕ → Type}
    (F : ∀ n, V n → ℝ → Matrix (Idx d (sz.L n) (sz.W n)) (Idx d (sz.L n) (sz.W n)) ℂ → ℝ)
    (ζ : ∀ n, V n → ℝ → ℝ) : GridTransferPT sz s t K F ζ := by
  intro hs hst hK hF
  have key : ∀ (n : ℕ) (p : Fin (K n + 1) × V n) (c : ℝ),
      pathP sz {ω | c < F n p.2 (gridTime s t K n p.1) (pathH sz s t K n p.1 ω)} =
        Sizes.seqP sz {ω | c < F n p.2 (gridTime s t K n p.1)
          (Sizes.seqHflow sz n (gridTime s t K n p.1) ω)} := by
    intro n p c
    have hS : MeasurableSet {M | c < F n p.2 (gridTime s t K n p.1) M} :=
      measurableSet_lt measurable_const (hF n p.2 _)
    have h1 := Measure.map_apply (μ := pathP sz) (transfer_measurable_pathH sz s t K n p.1) hS
    have h2 := Measure.map_apply (μ := Sizes.seqP sz)
      (transfer_measurable_seqHflow sz n (gridTime s t K n p.1)) hS
    have h3 := transferLaw sz s t K n p.1 (hs n) (hst n) (hK n)
    calc _ = (pathP sz).map (pathH sz s t K n p.1) {M | c < F n p.2 (gridTime s t K n p.1) M} :=
          h1.symm
      _ = (Sizes.seqP sz).map (Sizes.seqHflow sz n (gridTime s t K n p.1))
            {M | c < F n p.2 (gridTime s t K n p.1) M} := by rw [h3]
      _ = _ := h2
  simp only [PerTimeDomAt, key]

end RBM.Path

/-! ### Measurability of the resolvent entries and loops in the matrix argument
(RBM2D `Path/Transfer.lean:84–150`; `Gsig` becomes `Gres`, `gloop ∘ blockMat` becomes
`loopFine`) -/

namespace RBM.Gauss

section MeasurableMatrix

private theorem walk_measurable_matrix_inv_apply {n : Type*} [Fintype n] [DecidableEq n]
    {Θ : Type*} [MeasurableSpace Θ] {M : Θ → Matrix n n ℂ} (hM : Measurable M) (i j : n) :
    Measurable fun ω => (M ω)⁻¹ i j := by
  have h : (fun ω => (M ω)⁻¹ i j)
      = fun ω => Ring.inverse (M ω).det * (M ω).adjugate i j := by
    funext ω; rw [Matrix.inv_def]; rfl
  rw [h]
  refine Measurable.mul ?_ ?_
  · have hinv : Measurable (Ring.inverse : ℂ → ℂ) := by
      rw [Ring.inverse_eq_inv']; exact measurable_inv
    exact hinv.comp ((continuous_id.matrix_det).measurable.comp hM)
  · exact ((continuous_id.matrix_adjugate).measurable.comp hM).eval_matrix

set_option linter.unusedFintypeInType false in
private theorem walk_measurable_sub_smul_one {n : Type*} [Fintype n] [DecidableEq n]
    (z : ℂ) : Measurable fun M : Matrix n n ℂ => M - z • (1 : Matrix n n ℂ) :=
  (continuous_id.sub continuous_const).measurable

/-- The resolvent entry `Gres H z σ i j` is measurable in the matrix `H`
(`RBM2D/Path/Transfer.lean:103`, `transfer_measurable_Gsig`). -/
theorem walk_measurable_Gres_apply {n : Type*} [Fintype n] [DecidableEq n]
    (z : ℂ) (σ : Bool) (i j : n) : Measurable fun M : Matrix n n ℂ => Gres M z σ i j := by
  have h : ∀ w : ℂ,
      Measurable fun M : Matrix n n ℂ => Ring.inverse (M - w • (1 : Matrix n n ℂ)) i j := by
    intro w
    simpa [Matrix.nonsing_inv_eq_ringInverse] using
      walk_measurable_matrix_inv_apply (walk_measurable_sub_smul_one (n := n) w) i j
  cases σ
  · simpa [Gres] using h ((starRingEnd ℂ) z)
  · simpa [Gres] using h z

private theorem walk_measurable_mul {ι : Type*} [Fintype ι]
    {Θ : Type*} [MeasurableSpace Θ] {A C : Θ → Matrix ι ι ℂ}
    (hA : ∀ i j, Measurable fun x => A x i j) (hC : ∀ i j, Measurable fun x => C x i j)
    (i j : ι) : Measurable fun x => (A x * C x) i j := by
  simp only [Matrix.mul_apply]
  exact Finset.measurable_sum _ fun k _ => (hA i k).mul (hC k j)

variable (d L W : ℕ) [NeZero L] [NeZero W]

omit [NeZero W] in
private theorem walk_measurable_gloopProd (z : ℂ) (I : Loop.LoopIdx (Zd d L)) (i j : Vtx d L W) :
    Measurable fun H : Matrix (Vtx d L W) (Vtx d L W) ℂ => gloopProd d L W H z I i j := by
  suffices h : ∀ l : List (Bool × Zd d L), ∀ i j : Vtx d L W,
      Measurable fun H : Matrix (Vtx d L W) (Vtx d L W) ℂ => (l.foldr
        (fun (p : Bool × Zd d L) (Acc : Matrix (Vtx d L W) (Vtx d L W) ℂ) =>
          Gres H z p.1 * Eblk d L W p.2 * Acc)
        (1 : Matrix (Vtx d L W) (Vtx d L W) ℂ)) i j by
    simpa [gloopProd] using h (I.σ.zip I.a) i j
  intro l
  induction l with
  | nil => intro i j; simp
  | cons p l ih =>
      intro i j
      simp only [List.foldr_cons]
      refine walk_measurable_mul ?_ (fun a b => ih a b) i j
      intro a b
      refine walk_measurable_mul (fun c e => walk_measurable_Gres_apply z p.1 c e)
        (C := fun _ => Eblk d L W p.2) (fun _ _ => measurable_const) a b

omit [NeZero W] in
/-- The list-based loop `loopL H z I` is measurable in the matrix `H`
(`RBM2D/Path/Transfer.lean:134`, `transfer_measurable_gloop`). -/
theorem walk_measurable_loopL (z : ℂ) (I : Loop.LoopIdx (Zd d L)) :
    Measurable fun H : Matrix (Vtx d L W) (Vtx d L W) ℂ => loopL d L W H z I := by
  have h : ∀ H : Matrix (Vtx d L W) (Vtx d L W) ℂ, loopL d L W H z I
      = ∑ i : Vtx d L W, gloopProd d L W H z I i i := fun _ => rfl
  simp only [h]
  exact Finset.measurable_sum _ fun i _ => walk_measurable_gloopProd d L W z I i i

/-- `blockMat` is measurable (`RBM2D/Path/Transfer.lean:143`, `transfer_measurable_blockMat`). -/
theorem walk_measurable_blockMat :
    Measurable fun M : Matrix (Idx d L W) (Idx d L W) ℂ => blockMat d L W M :=
  (continuous_id.matrix_submatrix _ _).measurable

/-- The loop `loopFine H z σ a` of a flow matrix on the fine lattice (the matrix of `Lloop`) is
measurable in the matrix `H`. -/
theorem walk_measurable_loopFine (z : ℂ) {k : ℕ} (σ : Fin k → Bool) (a : Fin k → Zd d L) :
    Measurable fun H : Matrix (Idx d L W) (Idx d L W) ℂ => loopFine d L W H z σ a := by
  have h : ∀ H : Matrix (Idx d L W) (Idx d L W) ℂ, loopFine d L W H z σ a
      = loopL d L W (blockMat d L W H) z (loopOf σ a) := fun H => by
    unfold loopFine
    exact loopM_eq_loopL d L W _ _ _ _
  simp only [h]
  exact (walk_measurable_loopL d L W z (loopOf σ a)).comp (walk_measurable_blockMat d L W)

end MeasurableMatrix

namespace Sizes

variable {d : ℕ} (sz : Sizes d)

private theorem walk_measurable_seqHflow (n : ℕ) (u : ℝ) : Measurable (seqHflow sz n u) :=
  Measurable.of_eval_matrix _ fun i j => measurable_seqHflow_entry sz n u i j

/-- The entries of `G_t(σ)` are measurable random variables on the common sample space. -/
theorem walk_measurable_Gt_apply (n : ℕ) (E t : ℝ) (σ : Bool)
    (i j : Idx d (sz.L n) (sz.W n)) : Measurable fun ω : SeqΩ sz => Gt sz n E t σ ω i j :=
  (walk_measurable_Gres_apply (zt E t) σ i j).comp (walk_measurable_seqHflow sz n t)

/-- The loops `𝓛^{(k)}_{t,σ,a}` of the single-time flow are measurable random variables on the
common sample space. -/
theorem walk_measurable_Lloop (n : ℕ) (E t : ℝ) {k : ℕ} (σ : Fin k → Bool)
    (a : Fin k → Zd d (sz.L n)) : Measurable fun ω : SeqΩ sz => Lloop sz n E t σ a ω :=
  (walk_measurable_loopFine d (sz.L n) (sz.W n) (zt E t) σ a).comp (walk_measurable_seqHflow sz n t)

end Sizes

end RBM.Gauss

/-! ## Compiled nonempty instances at the preflight sequence `sz0`

`RBM.Gauss.SizesInst.sz0` (`RBM3D/Defs/Sizes.lean`): `d = 3`, `L_0 = 4`, `W_0 = 32`,
`lam_0 = 1/64`, `N_0 = 2097152`.  Grid data: `s = 1/10`, `t = 1`, `K = 4` (`Δ = 9/40`,
`u_2 = 11/20`) for the transfer law; `s = 1/10`, `t = 1/2`, `K = 4` (`Δ = 1/10`) for the
resolvent instances, where `η_u > 0` on the whole grid (`u_k ≤ 1/2 < 1`).  Every deterministic
hypothesis is discharged; nothing is assumed. -/

namespace RBM.Path.WalkInst

open RBM.Gauss RBM.Gauss.SizesInst

/-- The grid is nondegenerate: `u_2 = 1/10 + 2 · (1 - 1/10)/4 = 11/20`. -/
theorem gridTime_sz0 :
    gridTime (fun _ => (1 / 10 : ℝ)) (fun _ => 1) (fun _ => 4) 0 2 = 11 / 20 := by
  norm_num [gridTime, gridStep]

/-- The last grid time is `t` at the instance. -/
theorem gridTime_last_sz0 :
    gridTime (fun _ => (1 / 10 : ℝ)) (fun _ => 1) (fun _ => 4) 0 4 = 1 :=
  gridTime_last (fun _ => (1 / 10 : ℝ)) (fun _ => 1) (fun _ => 4) 0 (by norm_num)

/-- **`transferLaw` applied at concrete grid data** (`s = 1/10`, `t = 1`, `K = 4`, `n = 0`,
`k = 2`): the walk `√s X_0 + √Δ (X_1 + X_2)` has the law of `√(11/20) X` on the size-`0` matrices
of `sz0`; the three hypotheses `0 ≤ s`, `s ≤ t`, `K ≠ 0` are discharged. -/
theorem transferLaw_sz0 :
    (pathP sz0).map (pathH sz0 (fun _ => (1 / 10 : ℝ)) (fun _ => 1) (fun _ => 4) 0 2) =
      (Sizes.seqP sz0).map (Sizes.seqHflow sz0 0 (11 / 20)) := by
  have h := transferLaw sz0 (fun _ => (1 / 10 : ℝ)) (fun _ => 1) (fun _ => 4) 0 2
    (by norm_num) (by norm_num) (by norm_num)
  rwa [gridTime_sz0] at h

/-- **`transferLaw` as the pin**, at the instance sequence. -/
theorem transferLaw_pin_sz0 : TransferLaw sz0 := transferLaw sz0

/-- **`indepIncr` at the instance sequence, applied at `k = 2`**: the draw `3` is independent of
the filtration generated by the draws `0, 1, 2`. -/
theorem indepIncr_sz0 :
    Indep (filt sz0 2) (MeasurableSpace.comap (fun ω : PathΩ sz0 => ω (2 + 1)) inferInstance)
      (pathP sz0) := indepIncr sz0 2

/-- **`indepIncr` as the pin**, at the instance sequence. -/
theorem indepIncr_pin_sz0 : IndepIncr sz0 := indepIncr sz0

/-- Each increment has the model law `seqP sz0` (`map_incr` at the instance). -/
theorem map_incr_sz0 (k : ℕ) : (pathP sz0).map (fun ω : PathΩ sz0 => ω (k + 1)) = Sizes.seqP sz0 :=
  map_incr sz0 k

/-- **`precGrid_of_le` at the instance**: the entry `(0,0)` of the resolvent of the grid walk at
the grid time `u_2 = 3/10` (`s = 1/10`, `t = 1/2`, `K = 4`), at the flow value `z_t` of the energy
`E = 1/2` and `t = 1/2`, is `≺ η_t⁻¹` on the carrier `pathP`, at the scale `sz0.size`. -/
theorem gridRes_prec : sz0.PrecGrid (U := fun _ => Unit)
    (fun n _ ω => ‖Gres (pathH sz0 (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4) n 2 ω)
        (zt (1 / 2) (1 / 2)) true 0 0‖)
    (fun _ _ _ => (etaT (1 / 2 : ℝ) (1 / 2))⁻¹) := by
  have hpos : 0 < etaT (1 / 2 : ℝ) (1 / 2) := etaT_pos (by norm_num) (by norm_num)
  refine Sizes.precGrid_of_le sz0 (fun n _ _ => inv_nonneg.2 hpos.le) fun n _ ω => ?_
  have hz : (zt (1 / 2 : ℝ) (1 / 2)).im ≠ 0 := by
    rw [← etaT_eq_zt_im]; exact hpos.ne'
  have h := norm_inverse_entry_le
    (pathH_isHermitian sz0 (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4) n 2 ω) hz 0 0
  have habs : |(zt (1 / 2 : ℝ) (1 / 2)).im| = etaT (1 / 2 : ℝ) (1 / 2) := by
    rw [← etaT_eq_zt_im, abs_of_pos hpos]
  rw [habs] at h
  simpa [Gres] using h

/-- The matrix functional of the per-time instance: `‖G_u(+)_{00}‖` of the resolvent at
`z_u = zt (1/2) u`. -/
def Fres (n : ℕ) (_ : Unit) (u : ℝ)
    (M : Matrix (Idx 3 (sz0.L n) (sz0.W n)) (Idx 3 (sz0.L n) (sz0.W n)) ℂ) : ℝ :=
  ‖Gres M (zt (1 / 2) u) true 0 0‖

/-- The control `η_u⁻¹` (`η_u = etaT (1/2) u`). -/
def Zres (_ : ℕ) (_ : Unit) (u : ℝ) : ℝ := (etaT (1 / 2 : ℝ) u)⁻¹

theorem Fres_measurable (n : ℕ) (v : Unit) (u : ℝ) : Measurable (Fres n v u) :=
  (walk_measurable_Gres_apply (zt (1 / 2) u) true 0 0).norm

/-- The grid times of `s = 1/10`, `t = 1/2`, `K = 4` stay below `1/2`: `u_k = (k + 1)/10`. -/
theorem gridTime_le_half (n : ℕ) (k : Fin (4 + 1)) :
    gridTime (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4) n k ≤ 1 / 2 := by
  have hk : (k : ℕ) ≤ 4 := Nat.lt_succ_iff.1 k.is_lt
  have hk' : ((k : ℕ) : ℝ) ≤ 4 := by exact_mod_cast hk
  unfold gridTime gridStep
  norm_num
  linarith

/-- **`gridTransferPT` at the instance**: the per-time domination of the resolvent entry on the
single-time model (every grid time, by the deterministic Ward bound `|G_{xy}| ≤ η⁻¹`) transfers to
the grid walk.  The hypotheses `0 ≤ s`, `s ≤ t`, `K ≠ 0` and the measurability of the functional
are discharged; the parameter set is `Fin (K_n + 1) × Unit`, five grid times at each size. -/
theorem gridTransferPT_sz0 :
    PerTimeDomAt (pathP sz0) sz0.size (U := fun n => Fin ((fun _ : ℕ => 4) n + 1) × Unit)
      (fun n p ω => Fres n p.2
        (gridTime (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4) n p.1)
        (pathH sz0 (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4) n p.1 ω))
      (fun n p _ => Zres n p.2
        (gridTime (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4) n p.1)) := by
  refine (gridTransferPT sz0 (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4)
    (V := fun _ => Unit) Fres Zres (fun _ => by norm_num) (fun _ => by norm_num)
    (fun _ => by norm_num) Fres_measurable).2 ?_
  have hpos : ∀ u : ℝ, u ≤ 1 / 2 → 0 < etaT (1 / 2 : ℝ) u := fun u hu =>
    etaT_pos (by norm_num) (by linarith)
  refine Sizes.precPT_of_le sz0 (fun n p _ => ?_) fun n p ω => ?_
  · exact inv_nonneg.2 (hpos _ (gridTime_le_half n p.1)).le
  · have hu := hpos _ (gridTime_le_half n p.1)
    have hz : (zt (1 / 2 : ℝ)
        (gridTime (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4) n p.1)).im ≠ 0 := by
      rw [← etaT_eq_zt_im]; exact hu.ne'
    have h := norm_inverse_entry_le
      (Sizes.seqHflow_isHermitian sz0 n
        (gridTime (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4) n p.1) ω) hz 0 0
    have habs : |(zt (1 / 2 : ℝ)
        (gridTime (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4) n p.1)).im| =
        etaT (1 / 2 : ℝ)
          (gridTime (fun _ => (1 / 10 : ℝ)) (fun _ => 1 / 2) (fun _ => 4) n p.1) := by
      rw [← etaT_eq_zt_im, abs_of_pos hu]
    rw [habs] at h
    simpa [Fres, Zres, Gres] using h

end RBM.Path.WalkInst

end
