/-
Copyright (c) 2026 Jun Yin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jun Yin
-/
import Mathlib.Basic.Complex.Basic
import Mathlib.LinearAlgebra.Matrix.Circulant
import RBM3D.Defs.Lattice

/-!
# The block variance matrix `S^(B)(g)`

`(eq:variancematrix)` of Section 2.1 sets, for `a b : Z_L^d`,

  `S^(B)_{ab}(g) = (1 + 2 d g²)⁻¹ 1_{a = b} + g² (1 + 2 d g²)⁻¹ 1_{a ∼ b}`,

where `a ∼ b` means the two blocks are nearest neighbours.  Since `a ∼ b` depends only
on `a - b`, this is the circulant matrix generated by `RBM.sbKernel`.

Each point of `Z_L^d` has `2d` neighbours as soon as `3 ≤ L`, so the row sums are
`(1 + 2 d g²)⁻¹ (1 + 2 d g²) = 1` and `S^(B)(g)` is doubly stochastic.  For `L ≤ 2`
this fails -- for `L = 2` one has `1 = -1` in `ZMod 2`, so the `2d` neighbours collapse
to `d` -- and `3 ≤ L` is therefore carried as an explicit hypothesis, exactly as in the
sister projects.  See `docs/paper-deltas.md`.

At `g = 1` and `d = 1` this reduces to the `1/3` on `{0, 1, -1}` of `RBM1D`.
-/

namespace RBM

open Matrix

variable (d L : ℕ) (g : ℝ)

/-- The generating kernel of `S^(B)(g)`. -/
noncomputable def sbKernel : Zd d L → ℂ := fun x =>
  if x = 0 then ((1 + 2 * (d : ℝ) * g ^ 2)⁻¹ : ℝ)
  else if zdistD d L x = 1 then ((g ^ 2 * (1 + 2 * (d : ℝ) * g ^ 2)⁻¹ : ℝ) : ℂ)
  else 0

/-- The block variance matrix `S^(B)(g)` of `(eq:variancematrix)`. -/
noncomputable def SB : Matrix (Zd d L) (Zd d L) ℂ := circulant (sbKernel d L g)

theorem SB_apply (a b : Zd d L) : SB d L g a b = sbKernel d L g (a - b) := rfl

variable [NeZero L]

theorem sbKernel_neg (x : Zd d L) : sbKernel d L g (-x) = sbKernel d L g x := by
  simp only [sbKernel, neg_eq_zero, zdistD_neg]

/-- Property 1 of `lem_propTH` at the level of `S^(B)`: symmetry. -/
theorem SB_isSymm : (SB d L g).IsSymm := by
  rw [SB, circulant_isSymm_iff]
  exact sbKernel_neg d L g

theorem SB_transpose : (SB d L g)ᵀ = SB d L g := SB_isSymm d L g

omit [NeZero L] in
/-- Property 2 of `lem_propTH` at the level of `S^(B)`: translation invariance. -/
theorem SB_apply_add_right (a b c : Zd d L) : SB d L g (a + c) (b + c) = SB d L g a b := by
  simp only [SB_apply, add_sub_add_right_eq_sub]

end RBM
