/-
Copyright (c) 2026 Jun Yin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jun Yin
-/
import Mathlib.Basic.Complex.Basic
import Mathlib.LinearAlgebra.Matrix.Circulant
import Mathlib.Analysis.Complex.Basic
import Mathlib.Analysis.Matrix.Normed
import RBM3D.Defs.Neighbours

/-!
# The block variance matrix `S^(B)(g)`

`(eq:variancematrix)` of Section 2.1 sets, for `a b : Z_L^d`,

  `S^(B)_{ab}(g) = (1 + 2 d g²)⁻¹ 1_{a = b} + g² (1 + 2 d g²)⁻¹ 1_{a ∼ b}`,

where `a ∼ b` means the two blocks are nearest neighbours.  Since `a ∼ b` depends only
on `a - b`, this is the circulant matrix generated by `RBM.sbKernel`.

Each point of `Z_L^d` has `2d` neighbours as soon as `3 ≤ L`, so the row sums are
`(1 + 2 d g²)⁻¹ (1 + 2 d g²) = 1` and `S^(B)(g)` is doubly stochastic.  For `L ≤ 2`
this fails -- for `L = 2` one has `1 = -1` in `ZMod 2`, so the `2d` neighbours collapse
to `d` -- and `3 ≤ L` is therefore carried as an explicit hypothesis, exactly as in the
sister projects.  See `docs/paper-deltas.md`.

At `g = 1` and `d = 1` this reduces to the `1/3` on `{0, 1, -1}` of `RBM1D`.
-/

namespace RBM

open Matrix

variable (d L : ℕ) (g : ℝ)

/-- The generating kernel of `S^(B)(g)`. -/
noncomputable def sbKernel : Zd d L → ℂ := fun x =>
  if x = 0 then ((1 + 2 * (d : ℝ) * g ^ 2)⁻¹ : ℝ)
  else if zdistD d L x = 1 then ((g ^ 2 * (1 + 2 * (d : ℝ) * g ^ 2)⁻¹ : ℝ) : ℂ)
  else 0

/-- The block variance matrix `S^(B)(g)` of `(eq:variancematrix)`. -/
noncomputable def SB : Matrix (Zd d L) (Zd d L) ℂ := circulant (sbKernel d L g)

theorem SB_apply (a b : Zd d L) : SB d L g a b = sbKernel d L g (a - b) := rfl

variable [NeZero L]

theorem sbKernel_neg (x : Zd d L) : sbKernel d L g (-x) = sbKernel d L g x := by
  simp only [sbKernel, neg_eq_zero, zdistD_neg]

/-- Property 1 of `lem_propTH` at the level of `S^(B)`: symmetry. -/
theorem SB_isSymm : (SB d L g).IsSymm := by
  rw [SB, circulant_isSymm_iff]
  exact sbKernel_neg d L g

theorem SB_transpose : (SB d L g)ᵀ = SB d L g := SB_isSymm d L g

omit [NeZero L] in
/-- Property 2 of `lem_propTH` at the level of `S^(B)`: translation invariance. -/
theorem SB_apply_add_right (a b c : Zd d L) : SB d L g (a + c) (b + c) = SB d L g a b := by
  simp only [SB_apply, add_sub_add_right_eq_sub]

/-! ### Stochasticity: `S^(B) 1 = 1` and `‖S^(B)‖ = 1`

Both come from the same computation: the kernel is the real, non-negative function
`a·1_{x=0} + b·1_{|x|=1}` with `a = (1 + 2dg²)⁻¹`, `b = g²a`, and by the neighbour count
`card_nbhd` its total mass is `a + 2d·b = 1`.  No sign condition on `g` is needed. -/

section Stochastic

/-- The kernel of `S^(B)(g)` as a real function, split into its two pieces. -/
noncomputable def sbKernelR (x : Zd d L) : ℝ :=
  (if x = 0 then (1 + 2 * (d : ℝ) * g ^ 2)⁻¹ else 0) +
    (if zdistD d L x = 1 then g ^ 2 * (1 + 2 * (d : ℝ) * g ^ 2)⁻¹ else 0)

omit [NeZero L] in
theorem sbKernel_eq_ofReal (x : Zd d L) : sbKernel d L g x = (sbKernelR d L g x : ℂ) := by
  by_cases h0 : x = 0
  · subst h0; simp [sbKernel, sbKernelR]
  · by_cases h1 : zdistD d L x = 1 <;> simp [sbKernel, sbKernelR, h0, h1]

omit [NeZero L] in
theorem sbKernelR_nonneg (x : Zd d L) : 0 ≤ sbKernelR d L g x := by
  unfold sbKernelR
  have : 0 < 1 + 2 * (d : ℝ) * g ^ 2 := by positivity
  split_ifs <;> positivity

theorem sum_sbKernelR (hL : 3 ≤ L) : ∑ x, sbKernelR d L g x = 1 := by
  have hpos : 0 < 1 + 2 * (d : ℝ) * g ^ 2 := by positivity
  simp only [sbKernelR, Finset.sum_add_distrib, Finset.sum_ite_eq', Finset.mem_univ, ite_true,
    ← Finset.sum_filter, Finset.sum_const, card_nbhd d L hL, nsmul_eq_mul]
  push_cast
  field_simp

theorem sum_sbKernel (hL : 3 ≤ L) : ∑ x, sbKernel d L g x = 1 := by
  simp only [sbKernel_eq_ofReal, ← Complex.ofReal_sum, sum_sbKernelR d L g hL, Complex.ofReal_one]

theorem sum_norm_sbKernel (hL : 3 ≤ L) : ∑ x, ‖sbKernel d L g x‖ = 1 := by
  simp only [sbKernel_eq_ofReal, Complex.norm_real, Real.norm_of_nonneg (sbKernelR_nonneg d L g _),
    sum_sbKernelR d L g hL]

/-- Each row of `S^(B)(g)` sums to `1`. -/
theorem sum_SB_row (hL : 3 ≤ L) (a : Zd d L) : ∑ b, SB d L g a b = 1 := by
  rw [← sum_sbKernel d L g hL]
  exact Fintype.sum_equiv (Equiv.subLeft a) _ _ fun b => by rw [SB_apply]; rfl

/-- `S^(B)(g) 1 = 1`. -/
theorem SB_mulVec_one (hL : 3 ≤ L) : SB d L g *ᵥ (1 : Zd d L → ℂ) = 1 := by
  funext a
  simp only [Matrix.mulVec, dotProduct, Pi.one_apply, mul_one]
  exact sum_SB_row d L g hL a

theorem sum_norm_SB_row (hL : 3 ≤ L) (a : Zd d L) : ∑ b, ‖SB d L g a b‖ = 1 := by
  rw [← sum_norm_sbKernel d L g hL]
  exact Fintype.sum_equiv (Equiv.subLeft a) _ _ fun b => by rw [SB_apply]; rfl

open scoped NNReal Matrix.Norms.Operator

theorem sum_nnnorm_SB_row (hL : 3 ≤ L) (a : Zd d L) : ∑ b, ‖SB d L g a b‖₊ = 1 := by
  apply NNReal.eq
  rw [NNReal.coe_sum, NNReal.coe_one]
  exact sum_norm_SB_row d L g hL a

theorem nnnorm_SB (hL : 3 ≤ L) : ‖SB d L g‖₊ = 1 := by
  rw [Matrix.linfty_opNNNorm_def]
  simp only [sum_nnnorm_SB_row d L g hL]
  exact Finset.sup_const Finset.univ_nonempty 1

/-- `‖S^(B)(g)‖ = 1` in the `ℓ^∞` operator norm: the hypothesis `hS` of
`Propagator/Basic.lean`. -/
theorem norm_SB (hL : 3 ≤ L) : ‖SB d L g‖ = 1 := by
  rw [← coe_nnnorm, nnnorm_SB d L g hL, NNReal.coe_one]

end Stochastic

end RBM
