/-
Copyright (c) 2026 Jun Yin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jun Yin
-/
import RBM3D.Graph.LWVocab
import RBM3D.Graph.LWStein
import RBM3D.Graph.LWWeightExp
import RBM3D.Graph.LWGGExp
import RBM3D.Graph.LWExpTerm3

/-!
# LW-14e-1: the computable model and the AND-tree kernel certificate (leaf half of `LWG5Expand'`)

A computable model of the dotted partition `LGraph.partition` and of the `(Oe2x)` families on
`LGraph (Fin (a+1)) (Fin b)`, and the R-all AND-tree certificate `goodB` of height `3` for `LWG5Graph false s`
(both `s`), checked by the kernel (`decide +kernel`, no compiled evaluation).  This file holds the model, the assembly lemma
`goodB_succ_of`, and the non-vacuity instances; the chunk theorems are in `LWExpCertS0` (`s = false`) and
`LWExpCertS1` (`s = true`, `cert_all`).  Paper `B:66-69, 78-108` ("verified by inspecting", `B:98`).
All public names are in `namespace RBM.Graph.LWCert`.
-/

set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.unusedSectionVars false
set_option linter.unusedSimpArgs false
set_option linter.flexible false
set_option linter.style.whitespace false
set_option maxRecDepth 1000000

noncomputable section

open RBM.Gauss.Sizes

namespace RBM.Graph.LWCert

/-! ## 3. The computable model and the certificate functions

A model node is a real `LGraph (Fin (a+1)) (Fin b)` (external vertices `0..a`, internal `a+1..`) with the images of `x`, `y`;
every function below is computable on it and reduces in the kernel.  The coefficient field is never read (`m` is `1`).
The dotted partition is `LGraph.partition` with the noncomputable part (the quotient `Γ.Cls` of the `=`-dotted edges and
`vmapC`, `LWVocab.lean:735-778`) replaced by class labels `labsOf` (least vertex of the class) and a renumbering of the classes by
their least vertex (external classes first, because external vertices carry the least indices). -/

/-- A model node. -/
structure MNode where
  a : ℕ
  b : ℕ
  g : LGraph (Fin (a+1)) (Fin b)
  ext : Fin 2 → Fin (a+1)

instance : Inhabited MNode := ⟨⟨0, 0, ⟨[], [], [], 1⟩, fun _ => 0⟩⟩

section Flat

variable {a b : ℕ}

/-- The index of a vertex: external `0..a`, internal `a+1..`. -/
def vi (a b : ℕ) : Fin (a+1) ⊕ Fin b → ℕ := Sum.elim (fun i => i.val) (fun j => a + 1 + j.val)

/-- Union of the classes of the vertices `u`, `v` (class label = least vertex). -/
def unite (labs : List ℕ) (u v : ℕ) : List ℕ :=
  let lu := labs.getD u 0
  let lv := labs.getD v 0
  let m := min lu lv
  labs.map fun l => if l == lu || l == lv then m else l

/-- Class labels of the equivalence relation on `0..n-1` generated by the pairs `es`. -/
def labsOf (n : ℕ) (es : List (ℕ × ℕ)) : List ℕ := es.foldl (fun l e => unite l e.1 e.2) (List.range n)

/-- Class representatives (labels fixed by themselves). -/
def repsOf (labs : List ℕ) : List ℕ := (List.range labs.length).filter fun i => labs.getD i 0 == i

/-- The number of the class of `v` (classes ordered by least vertex). -/
def posOf (labs : List ℕ) (v : ℕ) : ℕ := ((List.range (labs.getD v 0)).filter fun i => labs.getD i 0 == i).length

/-- The index pair of a dotted edge. -/
def pairOf (a b : ℕ) (e : DEdge (Fin (a+1) ⊕ Fin b)) : ℕ × ℕ := (vi a b e.x, vi a b e.y)

/-- A vertex from a class number (total function; the junk branches are never taken). -/
def mkV (a' b' p : ℕ) : Fin (a'+1) ⊕ Fin b' :=
  if h : p < a' + 1 then Sum.inl ⟨p, h⟩
  else if hb : 0 < b' then Sum.inr ⟨(p - (a'+1)) % b', Nat.mod_lt _ hb⟩ else Sum.inl 0

/-- Merge of one dotted term `Δ` (`LGraph.merge`): the classes of the `=`-dotted edges become the vertices; `none` if a
`×`-dotted edge lies inside a class (`¬ Δ.Consistent`). -/
def cMerge (Δ : LGraph (Fin (a+1)) (Fin b)) (ext : Fin 2 → Fin (a+1)) : Option MNode :=
  let labs := labsOf (a + 1 + b) ((Δ.dotted.filter fun e => e.eq).map (pairOf a b))
  if (Δ.dotted.filter fun e => !e.eq).any (fun e => labs.getD (vi a b e.x) 0 == labs.getD (vi a b e.y) 0) then none
  else
    let reps := repsOf labs
    let A := (reps.filter (· < a + 1)).length
    let φ : Fin (a+1) ⊕ Fin b → Fin (A - 1 + 1) ⊕ Fin (reps.length - A) := fun v => mkV (A - 1) (reps.length - A) (posOf labs (vi a b v))
    some ⟨A - 1, reps.length - A,
      { solid := Δ.solid.map (SEdge.map φ), waved := Δ.waved.map (WEdge.map φ),
        dotted := (Δ.dotted.filter fun e => !e.eq).map (DEdge.map φ), coeff := Δ.coeff },
      fun i => match φ (Sum.inl (ext i)) with | Sum.inl j => j | Sum.inr _ => 0⟩

/-- The model of `LGraph.partition` (list-wise the same order): dotted choices, consistency, merge, weight split. -/
def cPartition (Γ : LGraph (Fin (a+1)) (Fin b)) (ext : Fin 2 → Fin (a+1)) : List MNode :=
  (Γ.dotChoices.map Γ.withDots).flatMap fun Δ =>
    match cMerge Δ ext with
    | none => []
    | some N => (N.g.splitWeights 1).map fun g => { N with g := g }

end Flat

section Cand

variable {a b : ℕ}

/-- A candidate of a model node (the data of `oe2x_graph_E`). -/
structure Cand (a b : ℕ) where
  x : Fin b
  y : Fin (a+1) ⊕ Fin b
  y' : Fin (a+1) ⊕ Fin b
  p : SEdge (Fin (a+1) ⊕ Fin b) × List (SEdge (Fin (a+1) ⊕ Fin b))
  q : SEdge (Fin (a+1) ⊕ Fin b) × List (SEdge (Fin (a+1) ⊕ Fin b))

/-- All candidates: an internal `x` with a blue uncircled non-loop out-edge `p.1` and in-edge `q.1`. -/
def cands (g : LGraph (Fin (a+1)) (Fin b)) : List (Cand a b) :=
  (lwSplit g.solid).flatMap fun p =>
    match p.1.src with
    | Sum.inl _ => []
    | Sum.inr x =>
      if p.1.σ && !p.1.circ && decide (p.1.dst ≠ Sum.inr x) then
        (lwSplit p.2).filterMap fun q =>
          if q.1.σ && !q.1.circ && decide (q.1.dst = Sum.inr x) && decide (q.1.src ≠ Sum.inr x) then
            some ⟨x, p.1.dst, q.1.src, p, q⟩ else none
      else []

/-- `I ⊕ Fin k` renumbered to `Fin (b + k)`. -/
def renum {k : ℕ} (h : LGraph (Fin (a+1)) (Fin b ⊕ Fin k)) : LGraph (Fin (a+1)) (Fin (b + k)) :=
  h.relabel (Sum.map id finSumFinEquiv)

/-- The graphs of `(Oe2x)` other than `R1` (the merged `oe2xR*`, `owxT1`, at `m = 1`; `R1` has value `0` on a normal graph,
see section 2), internal vertices renumbered. -/
def fams (g : LGraph (Fin (a+1)) (Fin b)) (c : Cand a b) : List (Σ b' : ℕ, LGraph (Fin (a+1)) (Fin b')) :=
  [⟨b, oe2xR2 1 g c.q c.x c.y c.y'⟩, ⟨b + 1, renum (owxT1 1 g c.x)⟩, ⟨b + 2, renum (oe2xR4 1 g c.q c.x c.y c.y')⟩,
   ⟨b + 1, renum (oe2xR5 1 g c.q c.x c.y c.y')⟩, ⟨b + 2, renum (oe2xR6 1 g c.q c.x c.y c.y')⟩] ++
  (lwSplit c.q.2).flatMap fun q' =>
    [⟨b + 1, renum (oe2xR7 1 g c.x c.y c.y' q')⟩, ⟨b + 2, renum (oe2xR8 1 g c.x c.y c.y' q')⟩]

end Cand

/-- The order target of a model node. -/
def tgt (N : MNode) : ℤ := if N.ext 0 = N.ext 1 then 4 else 5

/-- `ord ≥ tg`. -/
def leaf (N : MNode) : Bool := decide (tgt N ≤ N.g.scalingOrder)

/-- **The lite classification of the raw choices of a family graph `Δ`.**  For each consistent dotted choice the classes
(`labsOf`) give `B` internal vertices after the merge and `L` uncircled loops; the children (weight splits `t = 0..L`) have
`ord = n_S - t + 2 (n_W - B)`; only the children below the target are built (`cMerge`, `splitWeights`); for every choice with a
leaf variant the leaf properties `n_M ≤ 1`, `2 ≤ n_W`, `LWAttached`, "distinct external molecules or joined" are evaluated on the
molecule classes `mol` (waved edges added to the classes).  First component: all leaf properties hold. -/
def belowOf (Δ : LGraph (Fin (a+1)) (Fin b)) (ext : Fin 2 → Fin (a+1)) : Bool × List MNode :=
  let n := a + 1 + b
  let nS : ℤ := Δ.solid.length
  let nW : ℤ := Δ.waved.length
  let S : List (Bool × ℕ × ℕ) := Δ.solid.map fun e => (e.circ, vi a b e.src, vi a b e.dst)
  let X0 : List (ℕ × ℕ) := (Δ.dotted.filter fun e => !e.eq).map (pairOf a b)
  let E0 : List (ℕ × ℕ) := (Δ.dotted.filter fun e => e.eq).map (pairOf a b)
  let W : List (ℕ × ℕ) := Δ.waved.map fun e => (vi a b e.x, vi a b e.y)
  let x0 := vi a b (Sum.inl (ext 0))
  let y0 := vi a b (Sum.inl (ext 1))
  (Δ.dotChoices).foldr (fun c acc =>
    let E1 := (c.2.filter fun e => e.eq).map (pairOf a b)
    let X1 := (c.2.filter fun e => !e.eq).map (pairOf a b)
    let labs := labsOf n (E0 ++ E1)
    if (X0 ++ X1).any (fun e => labs.getD e.1 0 == labs.getD e.2 0) then acc
    else
      let B : ℤ := ((repsOf labs).filter (· ≥ a + 1)).length
      let L : ℤ := (S.filter fun e => !e.1 && labs.getD e.2.1 0 == labs.getD e.2.2 0).length
      let tg : ℤ := if labs.getD x0 0 == labs.getD y0 0 then 4 else 5
      let ok0 : Bool :=
        if nS + 2 * (nW - B) ≥ tg then
          let mol := W.foldl (fun l e => unite l e.1 e.2) labs
          let nMc := ((List.range n).filter fun i => i ≥ a + 1 && mol.getD i 0 == i).length
          nMc ≤ 1 && nW ≥ 2 &&
          ((List.range n).filter fun i => i ≥ a + 1 && mol.getD i 0 == i).all (fun i =>
            2 ≤ (S.filter fun e => mol.getD e.2.1 0 != mol.getD e.2.2 0 && (mol.getD e.2.1 0 == i || mol.getD e.2.2 0 == i)).length) &&
          (labs.getD x0 0 == labs.getD y0 0 || mol.getD x0 0 != mol.getD y0 0 || nMc == 0)
        else true
      if nS - L + 2 * (nW - B) ≥ tg then (ok0 && acc.1, acc.2)
      else
        match cMerge (Δ.withDots c) ext with
        | none => (ok0 && acc.1, acc.2)
        | some N => (ok0 && acc.1, ((N.g.splitWeights 1).map fun g => { N with g := g }).filter (fun M => !leaf M) ++ acc.2)) (true, [])

/-- The below-target children of a node at a candidate (all families), and the leaf-property flag. -/
def childrenB (N : MNode) (c : Cand N.a N.b) : Bool × List MNode :=
  (fams N.g c).foldr (fun f acc => let r := belowOf f.2 N.ext; (r.1 && acc.1, r.2 ++ acc.2)) (true, [])

/-- **The AND-tree certificate of height `n`**: a leaf, or a node with a candidate all of whose candidates have only good
below-target children (every candidate, so the certificate does not depend on a selection rule). -/
def goodB : ℕ → MNode → Bool
  | 0, N => leaf N
  | n + 1, N => leaf N || (!(cands N.g).isEmpty && (cands N.g).all fun c =>
      (childrenB N c).1 && (childrenB N c).2.all (goodB n))

/-- The root: `LWG5Graph k s` as a "family graph" with `x = 0`, `y = 1`: leaf-property flag of all its partition terms, and the
terms below the target (11 for every `(k, s)`). -/
def rootInfo (k s : Bool) : Bool × List MNode := belowOf (a := 1) (b := 3) (LWG5Graph k s) ![0, 1]

def rootAt (k s : Bool) (i : ℕ) : MNode := (rootInfo k s).2.getD i default

/-- Below-target children of `N` at its `j`-th candidate, and the flag. -/
def kids (N : MNode) (j : ℕ) : List MNode :=
  match (cands N.g)[j]? with | some c => (childrenB N c).2 | none => []

def kidsOk (N : MNode) (j : ℕ) : Bool :=
  match (cands N.g)[j]? with | some c => (childrenB N c).1 | none => true

def kid (N : MNode) (j l : ℕ) : MNode := (kids N j).getD l default

theorem all_of_getD {α : Type} [Inhabited α] (l : List α) (f : α → Bool) (h : ∀ i < l.length, f (l.getD i default) = true) :
    l.all f = true := by
  rw [List.all_eq_true]
  intro x hx
  obtain ⟨i, hi, rfl⟩ := List.getElem_of_mem hx
  have := h i hi
  rwa [List.getD_eq_getElem _ _ hi] at this

/-- Assembly of the certificate of a node from its candidates and the certificates of its below-target children. -/
theorem goodB_succ_of (n : ℕ) (N : MNode) (nc : ℕ) (hc : (cands N.g).length = nc) (hnc : 0 < nc)
    (hk : ∀ j < nc, kidsOk N j = true)
    (hch : ∀ j < nc, ∀ l < (kids N j).length, goodB n (kid N j l) = true) :
    goodB (n + 1) N = true := by
  unfold goodB
  have hne : (cands N.g).isEmpty = false := by
    cases h : cands N.g with
    | nil => rw [h] at hc; simp at hc; omega
    | cons _ _ => rfl
  rw [Bool.or_eq_true]
  right
  rw [hne]
  simp only [Bool.not_false, Bool.true_and, List.all_eq_true]
  intro c hc'
  obtain ⟨j, hj, hcj⟩ := List.getElem_of_mem hc'
  have hj' : j < nc := hc ▸ hj
  have h1 := hk j hj'
  have h2 := hch j hj'
  have hq : (cands N.g)[j]? = some c := by rw [List.getElem?_eq_getElem hj, hcj]
  have hk2 : kids N j = (childrenB N c).2 := by unfold kids; rw [hq]
  have hkid : ∀ l, kid N j l = (childrenB N c).2.getD l default := by intro l; unfold kid; rw [hk2]
  unfold kidsOk at h1
  rw [hq] at h1
  simp only at h1
  rw [h1, Bool.true_and]
  apply all_of_getD
  intro l hl
  have := h2 l (hk2 ▸ hl)
  rwa [hkid] at this


/-! ## The certificate: one inner node, the shapes, and non-vacuity instances -/

theorem inner_node_one : goodB 3 (rootAt false false 0) = true := by
  have h : (cands (rootAt false false 0).g).length = 2 ∧ ∀ j < 2, kidsOk (rootAt false false 0) j = true ∧ (kids (rootAt false false 0) j).length = 0 := by decide +kernel
  apply goodB_succ_of 2 _ 2 h.1 (by omega) (fun j hj => (h.2 j hj).1)
  intro j hj l hl
  have := (h.2 j hj).2
  omega

/-- The root has `163` partition terms, `11` below the target, and all leaf properties hold for the others. -/
theorem root_FF_shape : (rootInfo false false).1 = true ∧ (rootInfo false false).2.length = 11 := by decide +kernel
theorem root_FT_shape : (rootInfo false true).1 = true ∧ (rootInfo false true).2.length = 11 := by decide +kernel

/-- Instance (2): the root term `0` of `(k, s) = (false, false)` is not a leaf, has `scalingOrder 3`, target `4`,
`2` internal vertices and `2` candidates. -/
theorem lwCert_root0_nonleaf :
    leaf (rootAt false false 0) = false ∧ (rootAt false false 0).g.scalingOrder = 3 ∧
      tgt (rootAt false false 0) = 4 ∧ (rootAt false false 0).b = 2 ∧
      (cands (rootAt false false 0).g).length = 2 := by
  decide +kernel

/-- Instance (3): all `11` below-target root terms of both `s` are not leaves. -/
theorem lwCert_roots_below :
    (rootInfo false false).2.all (fun N => !leaf N) = true ∧
      (rootInfo false true).2.all (fun N => !leaf N) = true := by
  decide +kernel

#print axioms goodB_succ_of
#print axioms inner_node_one
#print axioms root_FF_shape
#print axioms root_FT_shape
#print axioms lwCert_root0_nonleaf
#print axioms lwCert_roots_below

end RBM.Graph.LWCert
